package providers

// registerBuiltin registra todos los proveedores integrados.
// Equivalente a los plugins/model-providers/ de hermes-agent.
func registerBuiltin(r *Registry) {
	for _, p := range builtinProviders {
		r.Register(p)
	}
}

// builtinProviders es la lista completa de proveedores integrados.
// Refleja los plugins de hermes-agent mas los proveedores locales.
var builtinProviders = []*ProviderProfile{

	// --- Suscripciones / OAuth ---

	{
		Name:        "nous",
		DisplayName: "Nous Portal",
		Description: "Suscripcion Nous Research. Login via navegador, sin API key manual.",
		SignupURL:   "https://portal.nousresearch.com",
		AuthType:    AuthTypeOAuthDevice,
		BaseURL:     "https://inference-api.nousresearch.com/v1",
		// OAuthPortalURL = device code endpoint para AuthTypeOAuthDevice
		OAuthPortalURL: "https://portal.nousresearch.com/api/oauth/device/code",
		OAuthTokenURL:  "https://portal.nousresearch.com/api/oauth/token",
		OAuthClientID:  "hermes-go",
		OAuthScopes:    []string{"inference offline_access"},
		FallbackModels: []string{"hermes-3-405b", "hermes-3-70b"},
		Aliases:        []string{"nous-portal", "portal"},
	},
	{
		Name:        "openai-codex",
		DisplayName: "OpenAI Codex",
		Description: "Requiere suscripcion ChatGPT Pro. Login via navegador.",
		SignupURL:   "https://chatgpt.com",
		AuthType:    AuthTypeOAuthExternal,
		BaseURL:     "https://api.openai.com/v1",
		OAuthPortalURL: "https://auth.openai.com/authorize",
		OAuthTokenURL:  "https://auth.openai.com/oauth/token",
		FallbackModels: []string{"codex-mini-latest", "o4-mini"},
		Aliases:        []string{"codex"},
	},
	{
		Name:        "copilot",
		DisplayName: "GitHub Copilot",
		Description: "Requiere suscripcion GitHub Copilot. Usa token de GitHub.",
		SignupURL:   "https://github.com/features/copilot",
		AuthType:    AuthTypeCopilot,
		BaseURL:     "https://api.githubcopilot.com",
		EnvVars:     []string{"COPILOT_GITHUB_TOKEN", "GH_TOKEN", "GITHUB_TOKEN"},
		FallbackModels: []string{"gpt-4o", "claude-opus-4-5"},
		Aliases:        []string{"github-copilot", "gh-copilot"},
	},
	{
		Name:        "xai-oauth",
		DisplayName: "xAI (Grok) OAuth",
		Description: "Requiere suscripcion xAI. Login via navegador.",
		SignupURL:   "https://x.ai",
		AuthType:    AuthTypeOAuthExternal,
		BaseURL:     "https://api.x.ai/v1",
		FallbackModels: []string{"grok-3", "grok-3-mini"},
		Aliases:        []string{"grok-oauth"},
	},
	{
		Name:        "minimax-oauth",
		DisplayName: "MiniMax OAuth",
		Description: "Requiere suscripcion MiniMax. Login via navegador.",
		SignupURL:   "https://minimax.io",
		AuthType:    AuthTypeOAuthExternal,
		BaseURL:     "https://api.minimax.io/v1",
		FallbackModels: []string{"MiniMax-M2.7"},
		Aliases:        []string{"minimax-subscription"},
	},
	{
		Name:        "qwen-oauth",
		DisplayName: "Qwen OAuth",
		Description: "Requiere cuenta Alibaba Cloud. Login via navegador.",
		SignupURL:   "https://qwenlm.ai",
		AuthType:    AuthTypeOAuthExternal,
		BaseURL:     "https://dashscope.aliyuncs.com/compatible-mode/v1",
		FallbackModels: []string{"qwen-max", "qwen-plus"},
		Aliases:        []string{"alibaba-oauth"},
	},

	// --- API Key ---

	{
		Name:        "openrouter",
		DisplayName: "OpenRouter",
		Description: "200+ modelos. Tier gratis disponible. Una sola clave para todos.",
		SignupURL:   "https://openrouter.ai",
		AuthType:    AuthTypeAPIKey,
		EnvVars:     []string{"OPENROUTER_API_KEY"},
		BaseURL:     "https://openrouter.ai/api/v1",
		ModelsURL:   "https://openrouter.ai/api/v1/models",
		FallbackModels: []string{
			"meta-llama/llama-3.3-70b-instruct",
			"google/gemini-2.0-flash-001",
		},
		DefaultAuxModel: "meta-llama/llama-3.1-8b-instruct",
		Aliases:         []string{"or"},
	},
	{
		Name:        "anthropic",
		DisplayName: "Anthropic",
		Description: "Claude Opus, Sonnet, Haiku.",
		SignupURL:   "https://console.anthropic.com",
		AuthType:    AuthTypeAPIKey,
		EnvVars:     []string{"ANTHROPIC_API_KEY", "ANTHROPIC_TOKEN"},
		BaseURL:     "https://api.anthropic.com/v1",
		FallbackModels: []string{"claude-opus-4-5", "claude-sonnet-4-5"},
		DefaultHeaders: map[string]string{
			"anthropic-version": "2023-06-01",
		},
		Aliases: []string{"claude"},
	},
	{
		Name:        "openai",
		DisplayName: "OpenAI",
		Description: "GPT-4o, o3, o4-mini.",
		SignupURL:   "https://platform.openai.com",
		AuthType:    AuthTypeAPIKey,
		EnvVars:     []string{"OPENAI_API_KEY"},
		BaseURL:     "https://api.openai.com/v1",
		FallbackModels: []string{"gpt-4o", "o4-mini"},
		Aliases:        []string{"gpt"},
	},
	{
		Name:        "nous-api",
		DisplayName: "Nous API",
		Description: "Nous Research via API key directa.",
		SignupURL:   "https://portal.nousresearch.com",
		AuthType:    AuthTypeAPIKey,
		EnvVars:     []string{"NOUS_API_KEY"},
		BaseURL:     "https://inference-api.nousresearch.com/v1",
		FallbackModels: []string{"hermes-3-405b"},
		Aliases:        []string{"nous-key"},
	},
	{
		Name:        "gemini",
		DisplayName: "Google Gemini",
		Description: "Gemini 2.0 Flash, Pro, Ultra.",
		SignupURL:   "https://aistudio.google.com",
		AuthType:    AuthTypeAPIKey,
		EnvVars:     []string{"GOOGLE_API_KEY", "GEMINI_API_KEY"},
		BaseURL:     "https://generativelanguage.googleapis.com/v1beta/openai",
		FallbackModels: []string{"gemini-2.0-flash", "gemini-1.5-pro"},
		Aliases:        []string{"google"},
	},
	{
		Name:        "groq",
		DisplayName: "Groq",
		Description: "Inferencia ultra-rapida. Tier gratis generoso.",
		SignupURL:   "https://console.groq.com",
		AuthType:    AuthTypeAPIKey,
		EnvVars:     []string{"GROQ_API_KEY"},
		BaseURL:     "https://api.groq.com/openai/v1",
		FallbackModels: []string{"llama-3.3-70b-versatile", "llama-3.1-70b-versatile"},
		Aliases:        []string{},
	},
	{
		Name:        "deepseek",
		DisplayName: "DeepSeek",
		Description: "DeepSeek V3, R1. Muy economico.",
		SignupURL:   "https://platform.deepseek.com",
		AuthType:    AuthTypeAPIKey,
		EnvVars:     []string{"DEEPSEEK_API_KEY"},
		BaseURL:     "https://api.deepseek.com/v1",
		FallbackModels: []string{"deepseek-chat", "deepseek-reasoner"},
		Aliases:        []string{},
	},
	{
		Name:        "xai",
		DisplayName: "xAI (Grok)",
		Description: "Grok 3, Grok 3 Mini.",
		SignupURL:   "https://x.ai",
		AuthType:    AuthTypeAPIKey,
		EnvVars:     []string{"XAI_API_KEY"},
		BaseURL:     "https://api.x.ai/v1",
		FallbackModels: []string{"grok-3", "grok-3-mini"},
		Aliases:        []string{"grok"},
	},
	{
		Name:        "together",
		DisplayName: "Together AI",
		Description: "Open source models, fine-tuning.",
		SignupURL:   "https://api.together.xyz",
		AuthType:    AuthTypeAPIKey,
		EnvVars:     []string{"TOGETHER_API_KEY"},
		BaseURL:     "https://api.together.xyz/v1",
		FallbackModels: []string{"meta-llama/Llama-3-70b-chat-hf"},
		Aliases:        []string{"together-ai"},
	},
	{
		Name:        "nvidia",
		DisplayName: "NVIDIA NIM",
		Description: "NVIDIA inference microservices.",
		SignupURL:   "https://build.nvidia.com",
		AuthType:    AuthTypeAPIKey,
		EnvVars:     []string{"NVIDIA_API_KEY"},
		BaseURL:     "https://integrate.api.nvidia.com/v1",
		FallbackModels: []string{"meta/llama-3.3-70b-instruct"},
		Aliases:        []string{"nim"},
	},
	{
		Name:        "minimax",
		DisplayName: "MiniMax",
		Description: "MiniMax M2.7 via API key.",
		SignupURL:   "https://minimax.io",
		AuthType:    AuthTypeAPIKey,
		EnvVars:     []string{"MINIMAX_API_KEY"},
		BaseURL:     "https://api.minimax.io/v1",
		FallbackModels: []string{"MiniMax-M2.7"},
		Aliases:        []string{},
	},
	{
		Name:        "kimi",
		DisplayName: "Kimi / Moonshot",
		Description: "Kimi k1.5, Moonshot v1.",
		SignupURL:   "https://platform.moonshot.cn",
		AuthType:    AuthTypeAPIKey,
		EnvVars:     []string{"KIMI_API_KEY", "MOONSHOT_API_KEY"},
		BaseURL:     "https://api.moonshot.cn/v1",
		FallbackModels: []string{"moonshot-v1-8k", "moonshot-v1-32k"},
		Aliases:        []string{"moonshot", "kimi-coding"},
	},
	{
		Name:        "huggingface",
		DisplayName: "Hugging Face",
		Description: "Inference Endpoints y modelos serverless.",
		SignupURL:   "https://huggingface.co",
		AuthType:    AuthTypeAPIKey,
		EnvVars:     []string{"HF_TOKEN", "HUGGINGFACE_API_KEY"},
		BaseURL:     "https://api-inference.huggingface.co/v1",
		Aliases:     []string{"hf"},
	},
	{
		Name:        "bedrock",
		DisplayName: "AWS Bedrock",
		Description: "Claude, Llama, Titan via AWS. Usa credenciales IAM, sin API key.",
		SignupURL:   "https://aws.amazon.com/bedrock",
		AuthType:    AuthTypeAWSSDK,
		BaseURL:     "https://bedrock-runtime.us-east-1.amazonaws.com",
		FallbackModels: []string{"anthropic.claude-opus-4-5-v1:0"},
		Aliases:        []string{"aws", "aws-bedrock"},
	},
	{
		Name:        "azure",
		DisplayName: "Azure OpenAI",
		Description: "OpenAI via Azure. Requiere endpoint propio.",
		SignupURL:   "https://azure.microsoft.com/en-us/products/ai-services/openai-service",
		AuthType:    AuthTypeAPIKey,
		EnvVars:     []string{"AZURE_OPENAI_API_KEY"},
		BaseURL:     "", // el usuario configura su endpoint en base_url
		Aliases:     []string{"azure-openai"},
	},

	// --- Locales (sin API key) ---

	{
		Name:        "ollama",
		DisplayName: "Ollama",
		Description: "Modelos locales. Sin API key. Inicia con: ollama serve",
		AuthType:    AuthTypeAPIKey,
		EnvVars:     []string{}, // sin env var, api_key = "ollama"
		BaseURL:     "http://localhost:11434/v1",
		FallbackModels: []string{"llama3.3", "qwen2.5-coder"},
		Aliases:        []string{},
	},
	{
		Name:        "lmstudio",
		DisplayName: "LM Studio",
		Description: "Modelos locales via LM Studio. Sin API key.",
		AuthType:    AuthTypeAPIKey,
		EnvVars:     []string{"LM_API_KEY"},
		BaseURL:     "http://localhost:1234/v1",
		Aliases:     []string{"lm-studio"},
	},
}
